#!/usr/bin/env python

# Configure script for LAIK:
# - tests for required/wanted packages
# - generates a Makefile.config

import os
import sys
import subprocess
import distutils.spawn

defs = ""
cc = "mpicxx"
omp_enabled = True
laik_root = ""

#------------------------------------
# Test HPC Environment
# On LRZ HPC Environment, optimize NUMA for better performance
#
hpc_found = os.path.exists("/lrz")
if hpc_found:
    print("Folder /lrz found. Assume LRZ HPC Environment")
    defs += " -D_HPC_"

#------------------------------------
# Laik Root
#
laik_found = os.path.exists("../laik")
if not laik_found:
    print("Folder ../laik not found. Please enter laik root")
    var = raw_input("Please enter something: ")
    laik_root += var
else:
    laik_root = "../laik"

# write Makefile.config, will be included by Makefile
cfile = open("Makefile.config", 'w')
cfile.write("# Generated by configure\n")
cfile.write("DEFS=" + defs + "\n")
cfile.write("LAIK_ROOT=" + laik_root + "\n")
if cc:
    cfile.write("CC=" + cc + "\n")
if omp_enabled:
    cfile.write("OMP_FLAGS=-fopenmp\n")
if "PREFIX" in os.environ:
    cfile.write("PREFIX=" + os.path.abspath(os.environ['PREFIX']) + "\n")
cfile.close()

print("Generated 'Makefile.config'")
